Adds "jade" to node deps
Prior to doing so, the npm action was throwing an error:

node_1        | internal/modules/cjs/loader.js:583
node_1        |     throw err;
node_1        |     ^
node_1        |
node_1        | Error: Cannot find module 'jade'
node_1        |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
node_1        |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
node_1        |     at Module.require (internal/modules/cjs/loader.js:637:17)
node_1        |     at require (internal/modules/cjs/helpers.js:22:18)
node_1        |     at Object.<anonymous> (/var/www/django/node_modules/jadeify/lib/jadeify.js:4:12)
node_1        |     at Module._compile (internal/modules/cjs/loader.js:689:30)
node_1        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
node_1        |     at Module.load (internal/modules/cjs/loader.js:599:32)
node_1        |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
node_1        |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Ran 'npm install jade' to get it into the package declaration. During
install, npm emitted a warning that "jade" has been renamed to "pug",
and recommended installing the latest pug. Deferring that change pending
a full audit of the node deps.